FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .
COPY backend/ ./backend/
COPY recommendsystem/ ./recommendsystem/
COPY 5-modelling/ ./5-modelling/
COPY Data/usecar_image/ ./Data/usecar_image/

EXPOSE 5001

CMD ["python", "app.py"]
